/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 peranuevaaa.glb --transform 
Files: peranuevaaa.glb [169.22KB] > C:\Users\Erick\Documents\3D models\Pera\peranuevaaa-transformed.glb [26.74KB] (84%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Peranuevaaa(props) {
  const { nodes, materials } = useGLTF('/peranuevaaa-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.251, 2.5, -0.229]} rotation={[-0.1, 3.5, 0.1]} scale={[0.064, 0.635, 0.064]}>
        <mesh geometry={nodes.Cylinder.geometry} material={materials.PaletteMaterial001} />
        <mesh geometry={nodes.Cylinder_1.geometry} material={materials.PaletteMaterial002} />
        <mesh geometry={nodes.Cylinder_2.geometry} material={materials.PaletteMaterial005} />
        <mesh geometry={nodes.Cylinder_3.geometry} material={materials.PaletteMaterial006} />
        <mesh geometry={nodes.Cylinder_4.geometry} material={materials.PaletteMaterial007} />
        <mesh geometry={nodes.Cylinder_5.geometry} material={materials.PaletteMaterial003} />
        <mesh geometry={nodes.Cylinder_6.geometry} material={materials.PaletteMaterial004} />
      </group>
    </group>
  )
}

useGLTF.preload('/peranuevaaa-transformed.glb')
